### PR TITLE
Convert a single geneId to symbol and add tests

### PR DESCRIPTION
**Pull request by lingyun1010**

### CODE REVIEW

**Comment by lingyun1010** [comment]
> Why have you copy-pasted the code to `atlas-web-single-cell` instead of using [the implementation in `atlas-web-core`](https://github.com/ebi-gene-expression-group/atlas-web-core/blob/master/src/main/java/uk/ac/ebi/atlas/bioentity/properties/BioEntityPropertyDao.java#L81)?

Yes, because I need a method with a single gene `String` input rather than a `Collection<String>` input parameter. I have tried to use the `getSymbolsForGeneIds`, however, as the structure of the cell type payload is complicated, I need to retrieve a single marker gene in the functional programming.

**Comment by alfonsomunozpomer** [comment]
Then you can use the original method passing a collection of one element, right? E.g. `ImmutableSet.of(geneId)`.

**Comment by upendrakumbham** [comment]
I would vote for Alfonso's review comment. Looks good for me apart from that.

**Comment by lingyun1010** [comment]
> Then you can use the original method passing a collection of one element, right? E.g. `ImmutableSet.of(geneId)`.

Right. Thanks for the comment. I will close this PR and amend the codes in `atlas-web-single-cell`.

**Pull request closed without merging**
