### PR TITLE
Change units of protein expression in baseline experiments

### PR DESCRIPTION
**Pull request by upendrakumbham**
This PR contains code changes to change protein expression units from `Any `to `PPB`. 
Simple PR for the review :).

### CODE REVIEW

**Review by alfonsomunozpomer — CHANGES_REQUESTED** [review]
`ExpressionUnitTest` isn’t passing. Could you please fix it? Since it’s a unit test you can run it. I’ve verified that the other integration tests are fine.

**Review by alfonsomunozpomer — APPROVED** [review]
All good.

**Comment by pcm32** [comment]
@upendrakumbham any reason not to merge this? Thanks!

**Comment by upendrakumbham** [comment]
Hi @pcm32, I thought that it was already merged. I'm doing it.

**Comment by upendrakumbham** [comment]
Done!

**Comment by pcm32** [comment]
Thanks!

**Pull request merged**
